{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-transformer",
    "version": "1.9.0-o",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.9.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-transformer-1.9.0-o.aar",
          "url": "media3-transformer-1.9.0-o.aar",
          "size": 409549,
          "sha512": "e7756f9282e3c85a7205f43c90bbe57b78acfad6ab2c86e3fe5a7ffb2f3e8fb8ef72badefa5f13a0a70de25f2e8b213c7c54d18f8305b7f0638834417ffc10a2",
          "sha256": "1234723316b371ea0ce03631b99954ca4a8fb2db0ccde3cb7736bf07b8c1d10c",
          "sha1": "7acff2a4cc9604b9414f8409f965899d737003cb",
          "md5": "b493544a1bcaef6f5eac8a66db8f62f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.9.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-transformer-1.9.0-o.aar",
          "url": "media3-transformer-1.9.0-o.aar",
          "size": 409549,
          "sha512": "e7756f9282e3c85a7205f43c90bbe57b78acfad6ab2c86e3fe5a7ffb2f3e8fb8ef72badefa5f13a0a70de25f2e8b213c7c54d18f8305b7f0638834417ffc10a2",
          "sha256": "1234723316b371ea0ce03631b99954ca4a8fb2db0ccde3cb7736bf07b8c1d10c",
          "sha1": "7acff2a4cc9604b9414f8409f965899d737003cb",
          "md5": "b493544a1bcaef6f5eac8a66db8f62f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-transformer-1.9.0-o-sources.jar",
          "url": "media3-transformer-1.9.0-o-sources.jar",
          "size": 279263,
          "sha512": "87f8d2be7cefff2429b6c96b5e19fb6d2f42b5c27bd7ad3bdb75f8c2f6d849617441a3e9b9eb2a4fb1f6b490e88f16f13408ee91c9dd715b50e7291cd1c9c563",
          "sha256": "e933b1bf521711424f81fa9c484ad07876ea1b5e2d5d34c6ec2f11098739e4be",
          "sha1": "49ff6d68a1aac06fd42d59a13cc3b4c6286a9915",
          "md5": "948072183959e22e0bcfb29215c52329"
        }
      ]
    }
  ]
}
