{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.0.aar",
          "url": "media3-common-1.11.0.aar",
          "size": 643136,
          "sha512": "e66bdab7e2419ce512e545d7dc047561bc21d53b76e0b6dfa8173bb199c0b6eea96697c0722b34469880d37ca3879eeb030e09cd96388851b29c1fb3501be1ec",
          "sha256": "2a92aae36c618a7967f70903417b6486d3bba9475eded889b53f98914af2f7d9",
          "sha1": "f37007cea140e6b9219fae009ecc18374e7fc1fa",
          "md5": "b924c11a93835b0726a3551f14c6ea17"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-ktor",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-av1",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-ffmpeg",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-flac",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-iamf",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-mpegh",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-opus",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder-vp9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect-lottie",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-effect-ndk",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector-frame",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose-material3",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.0.aar",
          "url": "media3-common-1.11.0.aar",
          "size": 643136,
          "sha512": "e66bdab7e2419ce512e545d7dc047561bc21d53b76e0b6dfa8173bb199c0b6eea96697c0722b34469880d37ca3879eeb030e09cd96388851b29c1fb3501be1ec",
          "sha256": "2a92aae36c618a7967f70903417b6486d3bba9475eded889b53f98914af2f7d9",
          "sha1": "f37007cea140e6b9219fae009ecc18374e7fc1fa",
          "md5": "b924c11a93835b0726a3551f14c6ea17"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.11.0-sources.jar",
          "url": "media3-common-1.11.0-sources.jar",
          "size": 525552,
          "sha512": "43736cb8988b3ff916b2c785df80f4a270b295e9486b7c658e32d9697f123c8d8d685bd9950b0ad422334b34adc58a08e3f6b6ff6f9cbf3486df691779d06a5b",
          "sha256": "a2219d8ba3a143fb9bd1b253e0bd31a3815f642b6d4e240b38673f4f3087a355",
          "sha1": "496ff80ad1e9a7c7c30f6c67c61d0c9ea8f20a78",
          "md5": "6255a985b8b761c26c910bdede8e9afd"
        }
      ]
    }
  ]
}
