{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.5.0.aar",
          "url": "media3-decode-opus-1.5.0.aar",
          "size": 532154,
          "sha512": "268f00547c414d3dc179cd547e49684ef965e8d850ba36f354aeaadd9ee22e66ad0e94564bde4492e47da19f302c60c101eb4dfcbf954568457ccc185d9f7224",
          "sha256": "eea247edef978ca9659f719b03e9b988246a4ebce49c9ba10d83a829262c921b",
          "sha1": "723db16e832ca3438651ba3dfd1d0a9772e60ff8",
          "md5": "69bad08a0da4833e3f6622d213b5faf9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.5.0.aar",
          "url": "media3-decode-opus-1.5.0.aar",
          "size": 532154,
          "sha512": "268f00547c414d3dc179cd547e49684ef965e8d850ba36f354aeaadd9ee22e66ad0e94564bde4492e47da19f302c60c101eb4dfcbf954568457ccc185d9f7224",
          "sha256": "eea247edef978ca9659f719b03e9b988246a4ebce49c9ba10d83a829262c921b",
          "sha1": "723db16e832ca3438651ba3dfd1d0a9772e60ff8",
          "md5": "69bad08a0da4833e3f6622d213b5faf9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.5.0-sources.jar",
          "url": "media3-decode-opus-1.5.0-sources.jar",
          "size": 9385,
          "sha512": "1a53b346e03bc292df05cc643fbbbcbe2243a7593e94efbbf81e5ac85dda98e68aa4ceda1ffd09c2fe2c59a7ce81e374f2af599e27b8199c4072b9f50860bbef",
          "sha256": "467ddfc5d6307c79927c870747adb773881e876d68985ed21d7a6464aa027448",
          "sha1": "1fdf93f3e864bd648632c7e84c59c4b9994512b9",
          "md5": "b911b1f79a30b9076faadd75fd1e3f8e"
        }
      ]
    }
  ]
}
