{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-av1",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0.aar",
          "url": "media3-decoder-av1-1.11.0.aar",
          "size": 2292490,
          "sha512": "e694d8d76f2d48d4e8a32be08942a5b7003fb2ef6158648e5fab4ea8eed67f38f66bbd27b44c2311c9b0e57610086402ed5c18feae6ec253b89f8e8875cc1701",
          "sha256": "173b3a14d0c7a606474b9d2c5e9ea70e94c6454091597fdf8f9117036f622f13",
          "sha1": "a78fca5e62230c1354709222a8588d530fff7ae1",
          "md5": "262cf3b33cfa0184c5baedf24c8f2544"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0.aar",
          "url": "media3-decoder-av1-1.11.0.aar",
          "size": 2292490,
          "sha512": "e694d8d76f2d48d4e8a32be08942a5b7003fb2ef6158648e5fab4ea8eed67f38f66bbd27b44c2311c9b0e57610086402ed5c18feae6ec253b89f8e8875cc1701",
          "sha256": "173b3a14d0c7a606474b9d2c5e9ea70e94c6454091597fdf8f9117036f622f13",
          "sha1": "a78fca5e62230c1354709222a8588d530fff7ae1",
          "md5": "262cf3b33cfa0184c5baedf24c8f2544"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0-sources.jar",
          "url": "media3-decoder-av1-1.11.0-sources.jar",
          "size": 11543,
          "sha512": "f6885d2a7c0c88a9dcedd2dc276f9d5a19a5783237b69f6980f8d5b00b046cfa10c8d3db9961536d62581c2ce38935b9d4dec38f4b71f32c4436f6d98be12cd7",
          "sha256": "332832813bd15ebde22ca951a5dbbffd7dc6e9c3ed1cdc60f58f7cb7dc4596e3",
          "sha1": "27fbcdc7214fa6d87fc64e24f1d581040d209b17",
          "md5": "0e46ed2c1f5449ab0becff6c2cdf38a1"
        }
      ]
    }
  ]
}
