{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-av1",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0.aar",
          "url": "media3-decoder-av1-1.11.0.aar",
          "size": 2292125,
          "sha512": "541e7271df9b052dfecebfcd6ff98ba5c94328cc349385cb179419bf9def913e143c4e3401dc838f812aca04906e9f4f44c0734d096e1d01e916b2b84dbd0b7a",
          "sha256": "b0c938e95596fc8574029ffc929c4ff7e981a1257aef22b46319d81ccdc83dcf",
          "sha1": "baf20d98d9944985b9c55fdd9d3e9603a11a65e0",
          "md5": "66d22fa226b56e3500d556db135d7749"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0.aar",
          "url": "media3-decoder-av1-1.11.0.aar",
          "size": 2292125,
          "sha512": "541e7271df9b052dfecebfcd6ff98ba5c94328cc349385cb179419bf9def913e143c4e3401dc838f812aca04906e9f4f44c0734d096e1d01e916b2b84dbd0b7a",
          "sha256": "b0c938e95596fc8574029ffc929c4ff7e981a1257aef22b46319d81ccdc83dcf",
          "sha1": "baf20d98d9944985b9c55fdd9d3e9603a11a65e0",
          "md5": "66d22fa226b56e3500d556db135d7749"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-av1-1.11.0-sources.jar",
          "url": "media3-decoder-av1-1.11.0-sources.jar",
          "size": 11543,
          "sha512": "f6885d2a7c0c88a9dcedd2dc276f9d5a19a5783237b69f6980f8d5b00b046cfa10c8d3db9961536d62581c2ce38935b9d4dec38f4b71f32c4436f6d98be12cd7",
          "sha256": "332832813bd15ebde22ca951a5dbbffd7dc6e9c3ed1cdc60f58f7cb7dc4596e3",
          "sha1": "27fbcdc7214fa6d87fc64e24f1d581040d209b17",
          "md5": "0e46ed2c1f5449ab0becff6c2cdf38a1"
        }
      ]
    }
  ]
}
