{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0.aar",
          "url": "media3-extractor-1.11.0.aar",
          "size": 823798,
          "sha512": "4ab0f2d9e1dc1bcd8d1e80bd14edff981bc5e4b8fd5000ec2b61c1f4e117bf5487b82e71f6ebf2f6c9b5929dbeea2162e8365d62baf2c2db604e274192574fef",
          "sha256": "d7f3753c54f588a69f8c6857a329d746018b35e5a2a40bdd4949c9cabe0973a9",
          "sha1": "b99068fd8943d1f862961fc2885225d46e6837a5",
          "md5": "6745958af305cef44f3b88b8d052f4f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0.aar",
          "url": "media3-extractor-1.11.0.aar",
          "size": 823798,
          "sha512": "4ab0f2d9e1dc1bcd8d1e80bd14edff981bc5e4b8fd5000ec2b61c1f4e117bf5487b82e71f6ebf2f6c9b5929dbeea2162e8365d62baf2c2db604e274192574fef",
          "sha256": "d7f3753c54f588a69f8c6857a329d746018b35e5a2a40bdd4949c9cabe0973a9",
          "sha1": "b99068fd8943d1f862961fc2885225d46e6837a5",
          "md5": "6745958af305cef44f3b88b8d052f4f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.11.0-sources.jar",
          "url": "media3-extractor-1.11.0-sources.jar",
          "size": 705562,
          "sha512": "569ffa7dc605945b6d15fb4f66ea6033e8d0a8633ebf1f3e218354be4d145cd3f93f3fe6757d9c41c5e25e1c7e9b0c52b08ec3fe1a0d0c82955531af5e860b0d",
          "sha256": "7347c8ed052ae2efe4a1f3aeb662b85e685805189ee46b53e8243e095ffebf20",
          "sha1": "bb7a1180edc5d74e9406f1935d1fd80a069c09b3",
          "md5": "7db60788f373035884b6efb48a82ddce"
        }
      ]
    }
  ]
}
