{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0.aar",
          "url": "media3-extractor-1.11.0.aar",
          "size": 847162,
          "sha512": "4f6727eb5818eaa06b1985b9263c8448df820c530c2f88769759a2e57a75b908258edd24fa0baf927f3d1928e6d3d2ca3265cb7f182038c21006265586aac770",
          "sha256": "4104eee07ca7b695357e77235e819cd104ec92eb738cea1f4fe57e609ecd9d4d",
          "sha1": "f2931cb39786d8fef44746bed7c2cd17ab552ac8",
          "md5": "27e2f53e42ba0f0af277758810901cea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0.aar",
          "url": "media3-extractor-1.11.0.aar",
          "size": 847162,
          "sha512": "4f6727eb5818eaa06b1985b9263c8448df820c530c2f88769759a2e57a75b908258edd24fa0baf927f3d1928e6d3d2ca3265cb7f182038c21006265586aac770",
          "sha256": "4104eee07ca7b695357e77235e819cd104ec92eb738cea1f4fe57e609ecd9d4d",
          "sha1": "f2931cb39786d8fef44746bed7c2cd17ab552ac8",
          "md5": "27e2f53e42ba0f0af277758810901cea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.11.0-sources.jar",
          "url": "media3-extractor-1.11.0-sources.jar",
          "size": 721171,
          "sha512": "4c202fabd3d8eb17cb75f21ba0b8da2d46f310685eb81c10afcef8a4ddfb2a3c885bf6085b7a305051cc1be0aebef50b2ce321d7e5d41e371b81208b78b40301",
          "sha256": "d188902832d5840b4e2df30b69da35a69cabb9b54e3360ff0f4169444f318797",
          "sha1": "97b58e1f79f218accc757679f2906a5cd61418a1",
          "md5": "5157c0489c602919af4f317be102a336"
        }
      ]
    }
  ]
}
