{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-rtsp",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.11.0.aar",
          "url": "media3-exoplayer-rtsp-1.11.0.aar",
          "size": 153930,
          "sha512": "14f96a55dd095e5e697eb39cc3b57e0f793037f13339113743c896e44dc943c21fc263cd7734ea51cc4d954963cd2105ab1ccab22b7bc9d3181046f6182a7831",
          "sha256": "a0afef37767e5def220c3f0a5e2ff26d4b568f93c2259797fc652fa76d65ac98",
          "sha1": "e7ada32af2cd8eecf4a54e9871ba4e481308c94b",
          "md5": "fedf1ec2351207f99bcd1c79f48a8865"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.11.0.aar",
          "url": "media3-exoplayer-rtsp-1.11.0.aar",
          "size": 153930,
          "sha512": "14f96a55dd095e5e697eb39cc3b57e0f793037f13339113743c896e44dc943c21fc263cd7734ea51cc4d954963cd2105ab1ccab22b7bc9d3181046f6182a7831",
          "sha256": "a0afef37767e5def220c3f0a5e2ff26d4b568f93c2259797fc652fa76d65ac98",
          "sha1": "e7ada32af2cd8eecf4a54e9871ba4e481308c94b",
          "md5": "fedf1ec2351207f99bcd1c79f48a8865"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.11.0-sources.jar",
          "url": "media3-exoplayer-rtsp-1.11.0-sources.jar",
          "size": 120726,
          "sha512": "16a608557d1812123da2c260dd113323a707c9633c08a4eb5621760f5442c5357b15bda4dfb45faf69b69005b2f7832213aab1bf944bee0812ffadc681945ef3",
          "sha256": "492f336e1e6e7b0c43f1ff5c08bb4718e61b7ba84ad1cb14b8db131db9dd99d6",
          "sha1": "d19cdbd9230aa732d6e9e69ee15358b9df83e96b",
          "md5": "9663715b5c40243852fa4b41ab7a7ee7"
        }
      ]
    }
  ]
}
