{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.9.0-o",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-o.aar",
          "url": "media3-exoplayer-1.9.0-o.aar",
          "size": 1649280,
          "sha512": "35bab6e60004cc52fff61efccffed83b042529be0b6dd24aba72c881df9d9218033afd5b51068da1317e92e0c4c8666991b45f59405b164be7b413df01527792",
          "sha256": "fdc492f42e09ad63223ef18b6a1aa46fc7c8be7061c51eea397af10559eba967",
          "sha1": "87f60880033d18dc9cc5ccc9f13631667e135877",
          "md5": "75cd67fcc674796cb1427257da290069"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-o.aar",
          "url": "media3-exoplayer-1.9.0-o.aar",
          "size": 1649280,
          "sha512": "35bab6e60004cc52fff61efccffed83b042529be0b6dd24aba72c881df9d9218033afd5b51068da1317e92e0c4c8666991b45f59405b164be7b413df01527792",
          "sha256": "fdc492f42e09ad63223ef18b6a1aa46fc7c8be7061c51eea397af10559eba967",
          "sha1": "87f60880033d18dc9cc5ccc9f13631667e135877",
          "md5": "75cd67fcc674796cb1427257da290069"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-o-sources.jar",
          "url": "media3-exoplayer-1.9.0-o-sources.jar",
          "size": 1178877,
          "sha512": "67894b50c605cbd01e3bec8143ea76dae8057394347db70408b25cc76c8667763b72d38f22c9ef4ff009d435a3ac19c220c3dfeb30cfea2023e1ad86a3b39934",
          "sha256": "117b184b95b1752955a1a1fbfaa1aebf29f3575900f08acde59ecaaf14efe620",
          "sha1": "5d4d33ee39f0fefeb6a036d6c0c88e50bd15b0bb",
          "md5": "0902cb3d76684f10839d162db23f77c3"
        }
      ]
    }
  ]
}
