{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-iamf",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0.aar",
          "url": "media3-decoder-iamf-1.11.0.aar",
          "size": 11926957,
          "sha512": "f93c1398206af9772d4ec752a969c4e9a34ac126f3f72cddace83344077260ac9b06ab89334d492ff5834937278e0cbf9c0211a3064787084a4eb4d78bcfb5fd",
          "sha256": "cab15e1a2be58d28a3658c87a084b43d6632aee9c4970f48f6d920337ca6e9e4",
          "sha1": "a8dfe01650f2df2dea7428a8716a126bc4c7a255",
          "md5": "87204f1a5419d5beefc56b729a64f527"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0.aar",
          "url": "media3-decoder-iamf-1.11.0.aar",
          "size": 11926957,
          "sha512": "f93c1398206af9772d4ec752a969c4e9a34ac126f3f72cddace83344077260ac9b06ab89334d492ff5834937278e0cbf9c0211a3064787084a4eb4d78bcfb5fd",
          "sha256": "cab15e1a2be58d28a3658c87a084b43d6632aee9c4970f48f6d920337ca6e9e4",
          "sha1": "a8dfe01650f2df2dea7428a8716a126bc4c7a255",
          "md5": "87204f1a5419d5beefc56b729a64f527"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0-sources.jar",
          "url": "media3-decoder-iamf-1.11.0-sources.jar",
          "size": 10758,
          "sha512": "bf4053afe46ac7845d77d22320a36467b52c662399257f8915f20e94cebd8349897d14ce5e04e56107c0238f046d01d2fcf418185ea6ead35c5e6598024a9cd4",
          "sha256": "cf31c3a765727b532bc2c39a2a0cc76f41c97cef233e220cddef602071d5c269",
          "sha1": "4771b9824ec8370593991b2405539d2cb669df8d",
          "md5": "309a4e033b9bc384fab0cc46f3364800"
        }
      ]
    }
  ]
}
