{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-iamf",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0.aar",
          "url": "media3-decoder-iamf-1.11.0.aar",
          "size": 11926949,
          "sha512": "40a110f25aff218d113f5075e96b12b4f91c09e4ef8fcc5cb9f98d471e51d6a05232bf168808cacf8933fd91b54d3e4c507663c65e2376638b4dbc2d1ed63b3c",
          "sha256": "19ffb2239a09949bfa868168d243783e5bf2c7c8559b3c72216483f2a5173b1a",
          "sha1": "81315b76138e6441f18aa6a0a82f4b2a641ffd60",
          "md5": "d0df298a19c17c417c3f2cd99c55cf68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0.aar",
          "url": "media3-decoder-iamf-1.11.0.aar",
          "size": 11926949,
          "sha512": "40a110f25aff218d113f5075e96b12b4f91c09e4ef8fcc5cb9f98d471e51d6a05232bf168808cacf8933fd91b54d3e4c507663c65e2376638b4dbc2d1ed63b3c",
          "sha256": "19ffb2239a09949bfa868168d243783e5bf2c7c8559b3c72216483f2a5173b1a",
          "sha1": "81315b76138e6441f18aa6a0a82f4b2a641ffd60",
          "md5": "d0df298a19c17c417c3f2cd99c55cf68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0-sources.jar",
          "url": "media3-decoder-iamf-1.11.0-sources.jar",
          "size": 10758,
          "sha512": "bf4053afe46ac7845d77d22320a36467b52c662399257f8915f20e94cebd8349897d14ce5e04e56107c0238f046d01d2fcf418185ea6ead35c5e6598024a9cd4",
          "sha256": "cf31c3a765727b532bc2c39a2a0cc76f41c97cef233e220cddef602071d5c269",
          "sha1": "4771b9824ec8370593991b2405539d2cb669df8d",
          "md5": "309a4e033b9bc384fab0cc46f3364800"
        }
      ]
    }
  ]
}
