{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-iamf",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0.aar",
          "url": "media3-decoder-iamf-1.11.0.aar",
          "size": 11926953,
          "sha512": "37055e251af65d3ed93154cb1f6e3999057c23f98c6ab1810e7fd2d6e955468729d2952332d6a643078f44bb362614a694b5c0c8401a424697c3d26c14b17077",
          "sha256": "27bc40cd78ff626493ff3420fe7ea463a5b5577c62357b473efa4f61163f3928",
          "sha1": "f0355aa69616610a93bf9376f0447fd099f33e40",
          "md5": "542c1a97737781b44d1c97d0c6921664"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0.aar",
          "url": "media3-decoder-iamf-1.11.0.aar",
          "size": 11926953,
          "sha512": "37055e251af65d3ed93154cb1f6e3999057c23f98c6ab1810e7fd2d6e955468729d2952332d6a643078f44bb362614a694b5c0c8401a424697c3d26c14b17077",
          "sha256": "27bc40cd78ff626493ff3420fe7ea463a5b5577c62357b473efa4f61163f3928",
          "sha1": "f0355aa69616610a93bf9376f0447fd099f33e40",
          "md5": "542c1a97737781b44d1c97d0c6921664"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-iamf-1.11.0-sources.jar",
          "url": "media3-decoder-iamf-1.11.0-sources.jar",
          "size": 10758,
          "sha512": "bf4053afe46ac7845d77d22320a36467b52c662399257f8915f20e94cebd8349897d14ce5e04e56107c0238f046d01d2fcf418185ea6ead35c5e6598024a9cd4",
          "sha256": "cf31c3a765727b532bc2c39a2a0cc76f41c97cef233e220cddef602071d5c269",
          "sha1": "4771b9824ec8370593991b2405539d2cb669df8d",
          "md5": "309a4e033b9bc384fab0cc46f3364800"
        }
      ]
    }
  ]
}
