{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-ffmpeg",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.0.aar",
          "url": "media3-decoder-ffmpeg-1.11.0.aar",
          "size": 11085505,
          "sha512": "31e878bf3f2870ed874a077f60f5ec039861462d0c3ddb323689686b8fbae9896402e280aa6d0be09c7e5623a972ca201ae289b79a1c74b8750326b453e59685",
          "sha256": "a2bfb74cc088331b6d7ebe58ed3102e121319f33e9c1b1bf2106a62e79d6f45a",
          "sha1": "e8ca4adaac47e40e8f1424c95824b2dade7a096b",
          "md5": "d0653c88e479cb35da6862af5b6b095a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.0.aar",
          "url": "media3-decoder-ffmpeg-1.11.0.aar",
          "size": 11085505,
          "sha512": "31e878bf3f2870ed874a077f60f5ec039861462d0c3ddb323689686b8fbae9896402e280aa6d0be09c7e5623a972ca201ae289b79a1c74b8750326b453e59685",
          "sha256": "a2bfb74cc088331b6d7ebe58ed3102e121319f33e9c1b1bf2106a62e79d6f45a",
          "sha1": "e8ca4adaac47e40e8f1424c95824b2dade7a096b",
          "md5": "d0653c88e479cb35da6862af5b6b095a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.0-sources.jar",
          "url": "media3-decoder-ffmpeg-1.11.0-sources.jar",
          "size": 17255,
          "sha512": "91f60faf18bafe7c162cbe18ba3630d100d4c7a685090a5e8bce360efed9510a0ecf74ee883dfc1f95ef166a2853842784182db09d01ac397f0b9498e919063e",
          "sha256": "8d84b233e4b498e349421f6d918269febc4d1a71fb98d133c60df23a4c6e667d",
          "sha1": "ccccb5d4e08cf83377e5832db02bf42012660f51",
          "md5": "69ef6070e4bcc07cc0a809ccf37e5d44"
        }
      ]
    }
  ]
}
