{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-ffmpeg",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.0.aar",
          "url": "media3-decoder-ffmpeg-1.11.0.aar",
          "size": 10975895,
          "sha512": "c5aeca81e63592417361e179a10cf4d1b733360670735184d4d0c4263fba0311d195f4fea09d9c17cb7284a7ea09e8a7caae8213163c62674e053ff3718f9dbc",
          "sha256": "febf9cd2211c06c700d3d90bb5bfa62a25f3e4da6ea9f0406f0ab60f5f631cc9",
          "sha1": "23c9acd10ba00a9d471660f617239f2ff30a19ee",
          "md5": "586b21b5869918c14e8b5385a72414c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.0.aar",
          "url": "media3-decoder-ffmpeg-1.11.0.aar",
          "size": 10975895,
          "sha512": "c5aeca81e63592417361e179a10cf4d1b733360670735184d4d0c4263fba0311d195f4fea09d9c17cb7284a7ea09e8a7caae8213163c62674e053ff3718f9dbc",
          "sha256": "febf9cd2211c06c700d3d90bb5bfa62a25f3e4da6ea9f0406f0ab60f5f631cc9",
          "sha1": "23c9acd10ba00a9d471660f617239f2ff30a19ee",
          "md5": "586b21b5869918c14e8b5385a72414c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-ffmpeg-1.11.0-sources.jar",
          "url": "media3-decoder-ffmpeg-1.11.0-sources.jar",
          "size": 17091,
          "sha512": "1994b1be6a014fffa517bca4b1c8c63c1a20ceffff22c1152184ed6f309c92b580e5e8dc327ef127cd6dfb06ad01cce2e781c406672f3ff1a379b6a066b65767",
          "sha256": "13370887ae5d8bca182ad305e2038f9055be1d825e7acfc86027e5638150d6a9",
          "sha1": "6b8e110512dd78a3b1a0963b8c5f05cf30bea979",
          "md5": "f3beabbd54827a010c0dc2c2abe30f8d"
        }
      ]
    }
  ]
}
