{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder-opus",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-opus-1.11.0.aar",
          "url": "media3-decoder-opus-1.11.0.aar",
          "size": 525123,
          "sha512": "b426d32a16c159ddd97f41cb474e8a44ed7ad5f2d8719917e174f6883c1e99c87ae0272d582518bbd803a2ddc69205335869a48ed8ebb9c04542c35edda63955",
          "sha256": "d03db52631fafe88414c2353a0006faf6377632ef2d54f5413b47964a64acd5e",
          "sha1": "3366f4211ac4e386c09353505f389bd882a99a30",
          "md5": "ee83cf16d6b04e8c7fbad3a525df2331"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-opus-1.11.0.aar",
          "url": "media3-decoder-opus-1.11.0.aar",
          "size": 525123,
          "sha512": "b426d32a16c159ddd97f41cb474e8a44ed7ad5f2d8719917e174f6883c1e99c87ae0272d582518bbd803a2ddc69205335869a48ed8ebb9c04542c35edda63955",
          "sha256": "d03db52631fafe88414c2353a0006faf6377632ef2d54f5413b47964a64acd5e",
          "sha1": "3366f4211ac4e386c09353505f389bd882a99a30",
          "md5": "ee83cf16d6b04e8c7fbad3a525df2331"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-opus-1.11.0-sources.jar",
          "url": "media3-decoder-opus-1.11.0-sources.jar",
          "size": 9101,
          "sha512": "647724b6fb0f01948bff21c4628dc764f154e6678ee844baa5094dccceeaf1399f1ecc63c8174e12e54133acea675fc1c7e9e9d7dea648b986e135c3f0713496",
          "sha256": "191bb995afb3b02e88ef7f13e65be88ab097309351e2e141f1a262b3a8a113f7",
          "sha1": "a67713bceb66faf42dab0ee410d9e950c3b48302",
          "md5": "9041f382a910ac707e2025e08563ac4c"
        }
      ]
    }
  ]
}
