{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.9.0-o",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.9.0-o.aar",
          "url": "media3-decode-opus-1.9.0-o.aar",
          "size": 524361,
          "sha512": "20600cc3afdefc9e1058a865ab68d99a0836949cd4f2d86d9d47637a59a721bcef78df4398cef95b97f854d63bfb3ddeaed2f83f47eea40adedd4e3e1825570f",
          "sha256": "ead4cb9fd0cd417b19a43792a38558e92e9a09f2606a5ccc7df35f2bc566d1fd",
          "sha1": "d1bb8ae7b2244d330b3abc8d056740d7356162d4",
          "md5": "b8dac9ccb4ddfa5ac4bba5e6d0962e5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-o"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.9.0-o.aar",
          "url": "media3-decode-opus-1.9.0-o.aar",
          "size": 524361,
          "sha512": "20600cc3afdefc9e1058a865ab68d99a0836949cd4f2d86d9d47637a59a721bcef78df4398cef95b97f854d63bfb3ddeaed2f83f47eea40adedd4e3e1825570f",
          "sha256": "ead4cb9fd0cd417b19a43792a38558e92e9a09f2606a5ccc7df35f2bc566d1fd",
          "sha1": "d1bb8ae7b2244d330b3abc8d056740d7356162d4",
          "md5": "b8dac9ccb4ddfa5ac4bba5e6d0962e5c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.9.0-o-sources.jar",
          "url": "media3-decode-opus-1.9.0-o-sources.jar",
          "size": 9389,
          "sha512": "6ae69bf27cf39f9adf1b371006f0deeb673a68a715eeb507df9eaa8ec54c11c59c43bbb1067bae8aa286d1592d7dfd3079f97e2bdfd2da19d55ba5ac0b022f38",
          "sha256": "b69524f55a98cccab9866f181555e3a33c33cb748fc346367f44986975f0a756",
          "sha1": "1e0f2d28519f5f68576ed03548c2b01aa7460903",
          "md5": "909395e8d48ce820bb53a5eb4f96e8ee"
        }
      ]
    }
  ]
}
