{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-rtsp",
    "version": "1.9.0-o",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.9.0-o.aar",
          "url": "media3-exoplayer-rtsp-1.9.0-o.aar",
          "size": 153500,
          "sha512": "7ab1423c01420224dbc38bfbf55611f2ab66091ed7f31304f1a667ff9ba30817d615bfd7003081f771c63e7efd64c94defc73a5e49a6715a0c889fa0eb29f0ad",
          "sha256": "6b2b1c78406dcf5d999ad5f00086fbc4644a50b307b4c71fcc003d7b22da1455",
          "sha1": "9e04b60fe06874b87f924e8c371b9dffd94ad66a",
          "md5": "a5e8b07b5cc576c266949592ae155a78"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.9.0-o.aar",
          "url": "media3-exoplayer-rtsp-1.9.0-o.aar",
          "size": 153500,
          "sha512": "7ab1423c01420224dbc38bfbf55611f2ab66091ed7f31304f1a667ff9ba30817d615bfd7003081f771c63e7efd64c94defc73a5e49a6715a0c889fa0eb29f0ad",
          "sha256": "6b2b1c78406dcf5d999ad5f00086fbc4644a50b307b4c71fcc003d7b22da1455",
          "sha1": "9e04b60fe06874b87f924e8c371b9dffd94ad66a",
          "md5": "a5e8b07b5cc576c266949592ae155a78"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-rtsp-1.9.0-o-sources.jar",
          "url": "media3-exoplayer-rtsp-1.9.0-o-sources.jar",
          "size": 120134,
          "sha512": "43283375604b166501b558dc3465c55a97ae064aee93dabbc3522b888e8ae729f27309b0da18eaecd212805c3cfc0b7ae8ea8753c6d1bcaf9cd10eceae9d3079",
          "sha256": "f4f800f643da1c416f539238f4c4622df9e296ccc7358caf7e1f9cb7d2b066fb",
          "sha1": "e6b3b3451ea77a20ccca70814fde0fae9bb66f17",
          "md5": "ed7dec6d7685cccea6c3274bf6f6a26a"
        }
      ]
    }
  ]
}
