{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-ima",
    "version": "1.9.0-o",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.38.0"
          },
          "excludes": [
            {
              "group": "androidx.media3",
              "module": "media3-common"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.9.0-o.aar",
          "url": "media3-exoplayer-ima-1.9.0-o.aar",
          "size": 90173,
          "sha512": "8b51358010bbd29a95d97009dc97d08bc1ddc2a97790c5dd3cdda837e700e5d086ff21b6f52bbef7b36556edc5254f58a4fb084c80dbaa6d8299cf40ffe6dd7b",
          "sha256": "7d4371c0a9178d6c33654420fc36dc7f78da899eb8ede9a70f14ca600114a086",
          "sha1": "5d4a10a0e33b1646fa67f2e960238c36d76c6b27",
          "md5": "43a9f05d49cb5e5e2642ee884d6c57dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.38.0"
          },
          "excludes": [
            {
              "group": "androidx.media3",
              "module": "media3-common"
            }
          ]
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0-o"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.9.0-o.aar",
          "url": "media3-exoplayer-ima-1.9.0-o.aar",
          "size": 90173,
          "sha512": "8b51358010bbd29a95d97009dc97d08bc1ddc2a97790c5dd3cdda837e700e5d086ff21b6f52bbef7b36556edc5254f58a4fb084c80dbaa6d8299cf40ffe6dd7b",
          "sha256": "7d4371c0a9178d6c33654420fc36dc7f78da899eb8ede9a70f14ca600114a086",
          "sha1": "5d4a10a0e33b1646fa67f2e960238c36d76c6b27",
          "md5": "43a9f05d49cb5e5e2642ee884d6c57dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-ima-1.9.0-o-sources.jar",
          "url": "media3-exoplayer-ima-1.9.0-o-sources.jar",
          "size": 50882,
          "sha512": "f987edce90580a9136f98a5b22b5c659cb46ef60c8dce53917614aee0cfcfe01afdd18586bc6aa8c73b645d22cb925be4b9523a6204968cbc54c5e0d7b43849b",
          "sha256": "0ee8d9240cdad6e8c490ecad9563396d6e6304c040d852c8ffd71a2ddf222841",
          "sha1": "498fa98148c0cb1196b338aa0a618a83d9c7e4e9",
          "md5": "ed13e967b1050e397b4964878cd00d9b"
        }
      ]
    }
  ]
}
